config/routes.rb
Rails.application.routes.draw do
  root :to => 'slider#index'
  resources :fotos
  resources :slider

end

app/models/foto.rb
class Foto < ActiveRecord::Base
	validates :nome, presence: true
	validates :retrato, presence: true
	has_attached_file :retrato, :styles => {:medium => '300x300>', :thumb => '80x80#' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(foto_params)

    respond_to do |format|
      if @foto.save
        format.html { redirect_to @foto, notice: 'A Foto foi criada corretamente.' }
        format.json { render :show, status: :created, location: @foto }
      else
        format.html { render :new }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'A foto foi editada com sucesso.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    @foto.destroy
    respond_to do |format|
      format.html { redirect_to fotos_url, notice: 'A foto foi excluída com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto
      @foto = Foto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def foto_params
      params.require(:foto).permit(:nome, :retrato)
    end
end

app/controllers/slider_controller.rb
class SliderController < ApplicationController
	def index
		@fotos = Foto.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/slider_helper.rb
module SliderHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto, :html => {:multipart => true}) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-12">
    <%= f.label :nome %>
  </div>

  <div class="col-md-12 elementDistance">
    <%= f.text_field :nome %>
  </div>

  <div class="col-md-12">
    <%= f.label :retrato %>
  </div>

  <div class="col-md-12 elementDistance">
    <%= f.file_field :retrato %>
  </div>
  <div class="col-md-12 elementDistance">
    <%= f.submit :value => 'Concluir', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Edição de Fotos</h1>
<hr/>

<%= render 'form' %>

<div class="col-md-12">
	<%= link_to fotos_path, class: 'btn btn-default' do %>
		<i class='fa fa-arrow-left'></i>
		Voltar
	<% end %>
</div>

app/views/fotos/index.html.erb
<h1>Lista de Fotos</h1>
<hr/>

<%= link_to new_foto_path, :class => 'btn btn-default' do %>
  <i class='fa fa-pencil'></i>
  Nova Foto
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Imagem</th>
      <th>Nome</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= image_tag(foto.retrato.url(:thumb)) %></td>
        <td><%= foto.nome %></td>
        <td><%= link_to (foto), class: 'btn btn-default' do %>
          <i class='fa fa-eye'></i>
          Visualizar
        <% end %>
        <%= link_to edit_foto_path(foto), class: 'btn btn-default' do %>
          <i class='fa fa-edit'></i>
          Editar
        <% end %>
        <%= link_to foto, method: :delete, data: { confirm: 'Tem certeza que deseja deletar a foto?' }, class: 'btn btn-default' do %>
          <i class='fa fa-trash-o'></i>
          Excluir          
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/fotos/new.html.erb
<h1>Nova Foto</h1>
<hr/>

<%= render 'form' %>

<div class="col-md-12">
	<%= link_to fotos_path, class: 'btn btn-default' do %>
		<i class='fa fa-arrow-left'></i>
		Voltar
	<% end %>
</div>

app/views/fotos/show.html.erb
<h1>Visualização de Fotos</h1>
<hr/>

<div class="col-md-12" id="notice"><%= notice %></div>

<div class="col-md-12">
  <strong>Nome:</strong>
</div>  

<div class="col-md-12 elementDistance">
  <%= @foto.nome %>
</div>

<div class="col-md-12">
  <strong>Imagem:</strong>
</div>

<div class="col-md-12 elementDistance">
  <%= image_tag(@foto.retrato.url(:medium)) %>
</div>

<div class="col-md-12">
	<%= link_to 'Editar', edit_foto_path(@foto), class: 'btn btn-primary' %> 
	<%= link_to 'Voltar', fotos_path, class: 'btn btn-default' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galeria</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>
	<nav class="navbar navbar-default navbar-fixed-top">
	   <ul class="nav navbar-nav">
	        <li>
				<%= link_to 'Slider', slider_index_path %>
	        </li>
	        <li>
				<%= link_to 'Galeria de Fotos', fotos_path %>		        
	        </li>
		</ul>
	</nav>
	<div class="container">
		<div class="row">
			<%= yield %>
		</div>
	</div>




</body>
</html>

app/views/slider/index.html.erb
<h1>Slider de Fotos</h1>
<hr/>

<% if (!@fotos.empty?) %>
	<div class="col-md-8 col-md-offset-2 elementDistance">
		<a id="back" class='leftArrow'/></a>
		<img width="550" height="400" id="sliderContainer">
		<a id="next" class='rightArrow'></a>
	</div>

	<div class="col-md-12 text-center">
		<span id='index'></span> de <%= @fotos.length %>
	</div>
<% else %>
	<p> Não há fotos adicionadas na galeria.</p>

	<%= link_to new_foto_path, :class => 'btn btn-default' do %>
	  <i class='fa fa-pencil'></i>
	  Nova Foto
	<% end %>
<% end %>